import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import programsRouter from "./programs";
import specialitiesRouter from "./specialities";
import unitsRouter from "./units";
import candidatesRouter from "./candidates";
import preferencesRouter from "./preferences";
import documentsRouter from "./documents";
import examsRouter from "./exams";
import questionsRouter from "./questions";
import examAssignmentsRouter from "./exam-assignments";
import attemptsRouter from "./attempts";
import interviewsRouter from "./interviews";
import panelRouter from "./panel";
import doctorsRouter from "./doctors";
import rankingsRouter from "./rankings";
import allocationsRouter from "./allocations";
import dashboardRouter from "./dashboard";
import importExcelRouter from "./import-excel";
import applicationFormsRouter from "./application-forms";
import seatMatrixRouter from "./seat-matrix";
import paymentSettingsRouter from "./payment-settings";
import storageRouter from "./storage";
import paymentRouter from "./payment";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(programsRouter);
router.use(specialitiesRouter);
router.use(unitsRouter);
router.use(candidatesRouter);
router.use(preferencesRouter);
router.use(documentsRouter);
router.use(examsRouter);
router.use(questionsRouter);
router.use(examAssignmentsRouter);
router.use(attemptsRouter);
router.use(interviewsRouter);
router.use(panelRouter);
router.use(doctorsRouter);
router.use(rankingsRouter);
router.use(allocationsRouter);
router.use(dashboardRouter);
router.use(importExcelRouter);
router.use(applicationFormsRouter);
router.use(seatMatrixRouter);
router.use(paymentSettingsRouter);
router.use(storageRouter);
router.use(paymentRouter);

export default router;
