"""Add address and joining_date

Revision ID: 6447958c981c
Revises: f22802ec2a16
Create Date: 2026-05-02 11:24:38.381965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6447958c981c'
down_revision: Union[str, Sequence[str], None] = 'f22802ec2a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('address', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('joining_date', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(), nullable=True))
    op.add_column('students', sa.Column('joining_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'address')
    op.drop_column('students', 'joining_date')
    op.drop_column('students', 'address')
    op.drop_column('doctors', 'joining_date')
    op.drop_column('doctors', 'address')
    # ### end Alembic commands ###
