"""Add new columns

Revision ID: b0611714eb92
Revises: 891fd40997c3
Create Date: 2026-05-02 11:13:07.224938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0611714eb92'
down_revision: Union[str, Sequence[str], None] = '891fd40997c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('psychometric_score', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('psychometric_recommendation', sa.String(), nullable=True))
    op.add_column('students', sa.Column('mcq_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mcq_total')
    op.drop_column('students', 'psychometric_recommendation')
    op.drop_column('students', 'psychometric_score')
    # ### end Alembic commands ###
