"""Add SeatMatrix

Revision ID: f22802ec2a16
Revises: b0611714eb92
Create Date: 2026-05-02 11:17:47.661812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22802ec2a16'
down_revision: Union[str, Sequence[str], None] = 'b0611714eb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_matrix', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_seat_matrix_id'), 'seat_matrix', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_matrix_id'), table_name='seat_matrix')
    op.drop_column('seat_matrix', 'id')
    # ### end Alembic commands ###
